Repository apollographql/apollo-link, pull requests merged in 2019-03, with the labels that each got.

#965 Attempt to fix out-of-memory Circle CI failures.
  .circleci/config.yml
  package-lock.json
  package.json
  packages/apollo-link-batch-http/package-lock.json
  packages/apollo-link-batch-http/package.json
  packages/apollo-link-batch/package-lock.json
  packages/apollo-link-batch/package.json
  packages/apollo-link-context/package-lock.json
  packages/apollo-link-context/package.json
  packages/apollo-link-dedup/package-lock.json
  packages/apollo-link-dedup/package.json
  packages/apollo-link-error/package-lock.json
  packages/apollo-link-error/package.json
  packages/apollo-link-http-common/package-lock.json
  packages/apollo-link-http-common/package.json
  packages/apollo-link-http/package-lock.json
  packages/apollo-link-http/package.json
  packages/apollo-link-polling/package-lock.json
  packages/apollo-link-polling/package.json
  packages/apollo-link-retry/package-lock.json
  packages/apollo-link-retry/package.json
  packages/apollo-link-schema/package-lock.json
  packages/apollo-link-schema/package.json
  packages/apollo-link-ws/package-lock.json
  packages/apollo-link-ws/package.json
  packages/apollo-link/package-lock.json
  packages/apollo-link/package.json
  packages/zen-observable-ts/package-lock.json
  packages/zen-observable-ts/package.json
  rollup.config.js
  scripts/minify
Labels: tooling

#966 Reduce bundlesize limits to reflect recent measurement changes.
  package.json
Labels: chore, tooling

#968 Avoid bundling graphql/execution/execute into apollo-link-schema.
  package.json
  packages/apollo-link-schema/src/__tests__/schemaLink.ts
  packages/apollo-link-schema/src/index.ts
  packages/apollo-link-schema/src/schemaLink.ts
  rollup.config.js
Labels: dependencies, enhancement, tooling

#969 Shrink apollo-link[-http-common] packages.
  package-lock.json
  package.json
  packages/apollo-link-http-common/package-lock.json
  packages/apollo-link-http-common/package.json
  packages/apollo-link-http-common/src/index.ts
  packages/apollo-link/package-lock.json
  packages/apollo-link/package.json
  packages/apollo-link/src/link.ts
  packages/apollo-link/src/linkUtils.ts
  packages/apollo-link/src/types.ts
  rollup.config.js
Labels: bundle size, enhancement, tooling

#970 chore: cut some low-hanging fruit in apollo-link
  packages/apollo-link/src/link.ts
Labels: bundle size

#971 chore: prune-low-hanging fruit in apollo-link-batch
  packages/apollo-link-batch-http/src/batchHttpLink.ts
  packages/apollo-link-batch/src/batchLink.ts
  packages/apollo-link-batch/src/batching.ts
Labels: bundle size

#972 Add .rpt2_cache to all packages/*/.npmignore files.
  CHANGELOG.md
  packages/apollo-link-batch-http/.npmignore
  packages/apollo-link-batch/.npmignore
  packages/apollo-link-context/.npmignore
  packages/apollo-link-dedup/.npmignore
  packages/apollo-link-error/.npmignore
  packages/apollo-link-http-common/.npmignore
  packages/apollo-link-http/.npmignore
  packages/apollo-link-polling/.npmignore
  packages/apollo-link-retry/.npmignore
  packages/apollo-link-schema/.npmignore
  packages/apollo-link-ws/.npmignore
  packages/apollo-link/.npmignore
  packages/zen-observable-ts/.npmignore
Labels: tooling

#992 Avoid importing graphql/language/printer for getKey.
  CHANGELOG.md
  packages/apollo-link/src/linkUtils.ts
Labels: bundle size, dependencies
